<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-scf196/blob/main/More_on_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [119]:
import numpy as np
np.__version__

'2.0.2'

In [120]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [121]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [122]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'

np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [123]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [124]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [125]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [126]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[-1.26731422, -0.85232797, -0.44002972],
        [ 0.85912137,  0.42434645,  2.40877075],
        [ 0.47593956,  1.20177558,  1.71439247]]),
 array([[0.60477422, 0.0798575 , 0.75136619],
        [0.49886779, 0.11174166, 0.75862255],
        [0.67693942, 0.45506428, 0.91188555]]))

In [127]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.

A = np.random.randn(5, 5)

B = 0.5 * (A + A.T)

C = 0.5 * (A - A.T)

A, B, C

(array([[ 0.02989302, -2.2272371 ,  1.04370039, -2.41473683,  1.28686457],
        [ 0.34166953,  0.08162809,  0.91334743,  1.50394134,  0.47021899],
        [-0.76981822,  1.36588979,  0.1840602 , -0.51216327,  0.18036005],
        [-0.73794112, -0.82585497, -1.23370158,  0.87670808, -1.94699341],
        [ 0.50609802, -0.51641797,  1.73822646, -0.57464057, -0.92999476]]),
 array([[ 0.02989302, -0.94278379,  0.13694109, -1.57633898,  0.89648129],
        [-0.94278379,  0.08162809,  1.13961861,  0.33904319, -0.02309949],
        [ 0.13694109,  1.13961861,  0.1840602 , -0.87293242,  0.95929325],
        [-1.57633898,  0.33904319, -0.87293242,  0.87670808, -1.26081699],
        [ 0.89648129, -0.02309949,  0.95929325, -1.26081699, -0.92999476]]),
 array([[ 0.        , -1.28445332,  0.9067593 , -0.83839785,  0.39038327],
        [ 1.28445332,  0.        , -0.22627118,  1.16489815,  0.49331848],
        [-0.9067593 ,  0.22627118,  0.        ,  0.36076916, -0.7789332 ],
        [ 0.83839785,

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [128]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [129]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [130]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [131]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences

In [132]:
# 1:
# np.matmul is used to find the matrix product of two arrays (array)
# np.dot is used to find the lement-wise multiplication of two arrays (array)
# @ is a shorthand for np.matmul
# * is a shorthand for np.dot

# 2:
A = np.array([[5,6],[7,8]])
B = np.array([[50,60],[70,80]])
np.matmul(A, B), np.dot(A, B), A @ B, A * B

(array([[ 670,  780],
        [ 910, 1060]]),
 array([[ 670,  780],
        [ 910, 1060]]),
 array([[ 670,  780],
        [ 910, 1060]]),
 array([[250, 360],
        [490, 640]]))

## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [133]:
import math

In [134]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

292 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [135]:
%%timeit
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

20.8 ms ± 3.43 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [136]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

From Gemini: "The %%timeit magic command is used in IPython environments (like Google Colab notebooks) to measure the execution time of a Python statement or block of code. It automatically runs the code multiple times and calculates the mean and standard deviation of the execution times, providing a more reliable performance measurement than a single run. It's very useful for comparing the efficiency of different approaches to solving a problem."

In [137]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

def harmonic_oscillator_energy(x, v, m, k):
  """
  Calculate the total energy of a harmonic oscillator system.

  Parameters:
  -----------
  x : np.ndarray
    Array of displacements.
  v : np.ndarray
    Array of velocities.
  m : float
    Mass of the oscillating particle.
  k : float
    Spring constant.

  Returns:
  --------
  kinetic_energy + potential_energy : np.ndarray
    Array of total energies for each corresponding x and v.
  """
  kinetic_energy = 0.5 * m * v**2
  potential_energy = 0.5 * k * x**2
  return kinetic_energy + potential_energy

mass = 5.0 # kg
spring_constant = 10.0 # N/m

x_values = np.array([0.1, 0.2, 0.3, 0.4, 0.5]) # meters
v_values = np.array([0.5, 0.4, 0.3, 0.2, 0.1]) # m/s

total_energies = harmonic_oscillator_energy(x_values, v_values, mass, spring_constant)

print("Calculated Total Energies:", total_energies)

Calculated Total Energies: [0.675 0.6   0.675 0.9   1.275]


## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [138]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
print("Eigenvalues:", vals)
print("Eigenvectors:", vecs)

Eigenvalues: [9.99658224e-17 1.00000000e+00 3.00000000e+00]
Eigenvectors: [[-5.77350269e-01 -7.07106781e-01  4.08248290e-01]
 [-5.77350269e-01  9.71445147e-17 -8.16496581e-01]
 [-5.77350269e-01  7.07106781e-01  4.08248290e-01]]


In [139]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

# vector [[-5.77350269e-01], [-5.77350269e-01], [-5.77350269e-01]] is associated with eigenvalue 0
# vector [[-7.07106781e-01], [9.71445147e-17], [7.07106781e-01]] is associated with eigenvalue 1
# vector [[4.08248290e-01], [-8.16496581e-01], [4.08248290e-01]] is associated with eigenvalue 3

## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [140]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [141]:
vals, vecs = np.linalg.eigh(K)
vals, vecs # entries of eigenvectors are all equal in magnitude to sqrt(2)/2

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [142]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [143]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.

U = vecs
U @ U.T, U.T @ U # equal & identity matrices

(array([[ 1.00000000e+00, -2.23711432e-17],
        [-2.23711432e-17,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -2.23711432e-17],
        [-2.23711432e-17,  1.00000000e+00]]))

In [151]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.

LAMBDA = U.T @ K @ U
print(LAMBDA)
print(vals)

# lambda11, lambda12, lambda 21 are close to 0, and lambda22 matches second eigenvalue

[[ 3.94430453e-31  6.65719202e-14]
 [-8.69285906e-14  4.90000000e+03]]
[   0. 4900.]


In [145]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule

Eigenvalue $0$ corresponds to a frequency of $0$, which corresponds to the first eigenvector's equal $x_1$ and $x_2$ components of $-\sqrt{2}$ and shows that the atoms are moving in the same direction with the same magnitude. Eigenvalue $4900$ corresponds to a frequency of $70$, and is represented with an eigenvector whose $x_1$ and $x_2$ compenents are equal in magnitude but opposite in direction $(-\sqrt{2}, \sqrt{2})$. The first mode is known as the zero-frequency mode, and the second mode is known as the normal mode.